[package]
name = "pallet-edge-ren-benchmarking"
version = "1.0.0"
authors = ["iStrike7 <siddiquishoeb.iitm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false }
frame-benchmarking = { version = "2.0.0", default-features = false}
frame-support = { version = "2.0.0", default-features = false}
frame-system = { version = "2.0.0", default-features = false}
sp-std = { version = "2.0.0", default-features = false }
sp-io = { version = "2.0.0", default-features = false }
sp-core = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
pallet-balances = { version = "2.0.0", default-features = false }
pallet-assets = { version = "2.0.0", default-features = false }
edge-ren = { version = "1.0.0", default-features = false, path = "../../edge-ren"}
edgeware-primitives = { path = "../../../node/primitives", default-features = false }

[dev-dependencies]
hex-literal = { version = "0.3.1" }

[features]
default = ["std"]
std = [
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"sp-std/std",
	"sp-io/std",
	"sp-core/std",
	"sp-runtime/std",
	"edgeware-primitives/std",
	"pallet-balances/std",
	"pallet-assets/std",
	"edge-ren/std",
]
